### ISSUE TITLE
SQLite transaction handling seems to fail

### ISSUE THREAD

**Issue by nikolauskrismer** [stkdiretto/diva2gtfs#1]
Great project. It helps me a lot :+1: 

I do get an sqlite error named "Safety level may not be changed inside a transaction".
A possible solution is described here:
https://github.com/hdbc/hdbc-sqlite3/issues/6#issuecomment-3050835

After commiting before setting "PRAGMA synchronous = OFF" and creating a new transaction afterwards things work well, but I wanted to double-check with you if this is really a solution or just something that hides the error message :-)

**Comment by stkdiretto** [comment]
Hey Nikolaus, thanks for the feedback and taking the time to open this issue!

Setting synchronous off is a dirty hack anyways, in my opinion. It's just that this was the quickest fix to get things running. If your solution works reproducibly better, I'd appreciate it very much if you opened a pull request so I can merge your approach into the tool.

I also appreciate any feedback about whether the DIVA conversion works with feeds from other agencies – either on github or via mail ;)

**Comment by nikolauskrismer** [comment]
Fixed that and added support for additional CRS (not only NBWT).
PR will be sent very soon :-)

**Comment by nikolauskrismer** [comment]
Fixed by #2
