### ISSUE TITLE
Empty GTFS with DINO data

### ISSUE THREAD

**Issue by yar-malik** [stkdiretto/diva2gtfs#9]
When I run

 `./all.sh ~/DINO\:DIVA/dino.zip dino` 

with my dino files that I got from  [Verkehr Rhein Rhuhr](https://www.openvrr.de/dataset/dino-daten/resource/f4188ef0-9523-4748-8d10-1725719a5c0d) I get the following errors: 

<img width="1212" alt="bildschirmfoto 2018-03-21 um 15 44 08" src="https://user-images.githubusercontent.com/4105873/37716550-14298656-2d1f-11e8-8897-1010e6cb306b.png">

**Comment by stkdiretto** [comment]
Thanks for the feedback! For `Switch.PM`, either `install Switch` in CPAN or install `libswitch-perl` through your package repository.

Unfortunately, DINO is a different breed from the DIVA files I got for my diploma thesis. The converter by bliksemlabs might be a better suited choice for the task, [see also here](https://github.com/OneBusAway/onebusaway-application-modules/issues/198)
